### ISSUE TITLE
Build API

### ISSUE THREAD

**Issue by kristlyuen** [preeformance/hsk#1]
- Pinyin
- English
- Traditional character
- Simplified character
- Word category (so we can sort/select by category)

@preeformance @rachelschipull Is there anything else you can think of that we'd need in the API?

**Comment by preeformance** [comment]
I'm thinking about the developer quiz and wondering if we need to add 3 "distractions" to each one?

**Comment by kristlyuen** [comment]
@preeformance I was thinking we'd pull in other words from the wordlist as the distractions. That should allow us to randomize the distractors.

**Comment by preeformance** [comment]
FINISHED! 
The API is sorted alphabetically by pinyin. Some of the words were tricky to categorize and I've created a new issue for that.
